# Stripe API Keys (test mode)
STRIPE_PUBLISHABLE_KEY = "pk_test_51T8FrQQ93cBuqRopwgYajqnqP2nlV1Qq2cSylT6HFvEYNcF9K4Vi2MK3Y2rJ6bQJ94uJW27MwUltTPE1DnbuExnm00qmU9FIj1"
STRIPE_SECRET_KEY = "sk_test_51T8FrQQ93cBuqRopxe7QWO3E6TfbxoLXYqLGAam2j6ysrzWZSCMJf05T1EWm5AH7fz67bmxXvAChcZF7C9EKuzpL00M5OAUJd1"
STRIPE_BASIC_PRICE_ID = "price_1T8GEnQ93cBuqRopZW3dcjyg"
STRIPE_PLUS_PRICE_ID = "price_1T8GKBQ93cBuqRopPrWJYK9D"
STRIPE_PREMIUM_PRICE_ID = "price_1T8GMXQ93cBuqRopTgPSeljT"
TESTING_MODE = true
